#!/bin/bash
# Usage: sh tree 'make the red square blue'
# 		 -w shows the parsed tree in a browser
# Note: bitpar must be in your path for this to work


PARSE=$(echo $1 | tr ' ' '\12'  |  bitpar -v -q hci.gram hci.lex  | tr '(' '[' | tr ')' ']')
echo $PARSE
F_PARSE=$(echo $PARSE | sed 's/ /%20/g')
if [[ $2 = '-w' ]]; then
	python -mwebbrowser http://mshang.ca/syntree/?$F_PARSE 2> /dev/null
fi